"use client";

import Link from "next/link";
import { ChangeEvent, useEffect, useState } from "react";

type GradeRow = { grade: { id: string; targetType: string; targetId: string; rawValue: string; normalizedPercentage: string; status: string }; studentName: string; studentEmail: string | null };

export default function Gradebook({ classroomId, classroomName, initialScale }: { classroomId: string; classroomName: string; initialScale: { type: string; min: number; max: number; passThreshold: number } }) {
  const [rows, setRows] = useState<GradeRow[]>([]); const [csv, setCsv] = useState(""); const [preview, setPreview] = useState<{ accepted: number; rejected: number; errors: Array<{ row: number; reason: string }> } | null>(null); const [message, setMessage] = useState(""); const endpoint = `/api/classrooms/${classroomId}/grades`;
  function load() { void fetch(endpoint).then((response) => response.json()).then((body) => setRows(body.grades ?? [])); }
  useEffect(() => { let active = true; void fetch(endpoint).then((response) => response.json()).then((body) => { if (active) setRows(body.grades ?? []); }); return () => { active = false; }; }, [endpoint]);
  async function readFile(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setCsv(await file.text()); }
  async function validate(confirm = false) { const response = await fetch(endpoint, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ csv, confirm, fileName: "grades.csv" }) }); const body = await response.json(); setPreview(body.preview ?? body.summary ?? null); setMessage(response.ok ? confirm ? "Importación publicada y auditada." : "Vista previa lista." : body.error ?? "No se pudo validar."); if (response.ok && confirm) load(); }
  async function saveScale(form: HTMLFormElement) { const values = new FormData(form); const type = String(values.get("type")); const min = Number(values.get("min")); const max = Number(values.get("max")); const passThreshold = Number(values.get("passThreshold")); const response = await fetch(`/api/classrooms/${classroomId}/settings`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(type === "rubric_levels" ? { type, min, max, passThreshold, levels: ["Inicial", "En desarrollo", "Competente", "Avanzado"] } : { type, min, max, passThreshold }) }); const body = await response.json(); setMessage(response.ok ? "Escala actualizada para futuras publicaciones." : body.error ?? "No se pudo actualizar la escala."); }
  async function uploadMaterial(form: HTMLFormElement) { const values = new FormData(form); values.set("classroomId", classroomId); const response = await fetch("/api/teacher/materials", { method: "POST", body: values }); const body = await response.json(); setMessage(response.ok ? "Material privado cargado. Los TXT extraídos pueden usarse en el copiloto." : body.error ?? "No se pudo cargar el material."); if (response.ok) form.reset(); }
  return <main className="studio-shell"><nav className="studio-nav"><Link className="brand" href="/classrooms"><span className="brand-block">E</span><span>EDU<br/><i>SIGNAL</i></span></Link><span className="teacher-chip">LIBRO DE CALIFICACIONES</span></nav><header className="studio-hero compact-hero"><p>{classroomName}</p><h1>Calificaciones<br/><em>con trazabilidad.</em></h1><div className="activity-actions"><a className="soft" href={`${endpoint}?format=template`}>Descargar plantilla CSV</a><a className="primary" href={`${endpoint}?format=csv`}>Exportar publicadas</a></div></header><section className="workspace-grid"><section className="workspace-list"><h2>Publicadas</h2>{rows.map((row) => <article className="workspace-item" key={row.grade.id}><div><b>{row.studentName}</b><p>{row.grade.targetType} · {row.grade.targetId}</p></div><strong>{row.grade.rawValue} · {row.grade.normalizedPercentage}%</strong></article>)}</section><section className="modal workspace-form"><form onSubmit={(event) => { event.preventDefault(); void saveScale(event.currentTarget); }}><h2>Escala oficial</h2><label>Tipo<select name="type" defaultValue={initialScale.type}><option value="numeric_5">0-5</option><option value="numeric_10">0-10</option><option value="numeric_100">0-100</option><option value="rubric_levels">Niveles de rúbrica</option></select></label><div className="form-row"><label>Mínimo<input name="min" type="number" defaultValue={initialScale.min} /></label><label>Máximo<input name="max" type="number" defaultValue={initialScale.max} /></label><label>Aprobación<input name="passThreshold" type="number" defaultValue={initialScale.passThreshold} /></label></div><button className="soft">Guardar escala</button></form><hr/><form onSubmit={(event) => { event.preventDefault(); void uploadMaterial(event.currentTarget); }}><h2>Material privado</h2><input name="file" type="file" required accept=".pdf,.docx,.pptx,.txt,.png,.jpg,.jpeg,.webp" /><button className="soft">Cargar material</button></form><hr/><h2>Importar CSV</h2><input type="file" accept=".csv,text/csv" onChange={(event) => void readFile(event)} /><label>Contenido para validar<textarea rows={10} value={csv} onChange={(event) => setCsv(event.target.value)} /></label><div className="activity-actions"><button className="soft" disabled={!csv} onClick={() => void validate(false)}>Validar vista previa</button><button className="primary" disabled={!preview || preview.rejected > 0 || preview.accepted === 0} onClick={() => void validate(true)}>Confirmar importación</button></div>{preview && <article className="student-activity-card"><b>{preview.accepted} válidas · {preview.rejected} rechazadas</b>{preview.errors.map((error) => <p key={`${error.row}-${error.reason}`}>Fila {error.row}: {error.reason}</p>)}</article>}{message && <p role="status">{message}</p>}</section></section></main>;
}
