"use client";
import { useState } from "react";

type Rubric = { rubric: { id: string; title: string }; criteria: Array<{ id: string; name: string; maxScore: string }> };
export default function EvidenceEvaluation({ evidenceId, rubrics, evaluations }: { evidenceId: string; classroomId: string; rubrics: Rubric[]; evaluations: Array<{ evaluation: { rubricId: string | null; score: string | null; feedback: string | null }; scores: Array<{ criterionId: string; score: string; feedback: string | null }> }> }) {
  const [rubricId, setRubricId] = useState(rubrics[0]?.rubric.id ?? ""); const [score, setScore] = useState(""); const [feedback, setFeedback] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const rubric = rubrics.find((item) => item.rubric.id === rubricId);
  async function submit() { setSaving(true); const scores = (rubric?.criteria ?? []).map((criterion) => ({ criterionId: criterion.id, score: (document.querySelector(`[data-criterion="${criterion.id}"]`) as HTMLInputElement)?.value, feedback: null })); const response = await fetch("/api/evaluations", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ evidenceId, rubricId: rubricId || undefined, score: score || undefined, feedback, scores }) }); const data = await response.json().catch(() => ({})); setMessage(response.ok ? "Evaluación guardada." : data.error ?? "No se pudo guardar."); setSaving(false); }
  return <section className="modal"><h2>Evaluación</h2>{evaluations.length > 0 && <p id="evaluation-existing" role="status">Ya existe una evaluación para esta evidencia. No puede modificarse.</p>}<fieldset disabled={saving || evaluations.length > 0}><legend className="sr-only">Datos de evaluación</legend><label>Rúbrica<select value={rubricId} onChange={(event) => setRubricId(event.target.value)}><option value="">Evaluación global</option>{rubrics.map((item) => <option key={item.rubric.id} value={item.rubric.id}>{item.rubric.title}</option>)}</select></label>{rubric?.criteria.map((criterion) => <label key={criterion.id}>{criterion.name} (máx. {criterion.maxScore})<input data-criterion={criterion.id} type="number" min="0" max={criterion.maxScore} step="any" required /></label>)}{!rubricId && <label>Puntuación global (0-100)<input type="number" min="0" max="100" value={score} onChange={(event) => setScore(event.target.value)} required /></label>}<label>Feedback<textarea value={feedback} onChange={(event) => setFeedback(event.target.value)} /></label><button className="primary" onClick={submit}>{saving ? "Guardando…" : "Guardar evaluación"}</button></fieldset>{message && <p role="status">{message}</p>}</section>;
}
