"use client";

import { useState } from "react";
import Link from "next/link";

const highlights = [
  ["Estudiantes", "Gestiona perfiles, matrículas y trayectos.", "/students", "LP"],
  ["Evidencias", "Convierte actividades en señales verificables.", "/evidence", "✦"],
  ["Rúbricas", "Evalúa con criterios claros y compartidos.", "/rubrics", "✓"],
];

export default function Dashboard({ user }: { user: { displayName: string; email: string } }) {
  const [toast, setToast] = useState("");
  const initials = user.displayName.split(/\s+/).map((word) => word[0]).join("").slice(0, 2).toUpperCase();
  async function signOut() { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }
  return <main className="shell"><div className="ambient ambient-one" /><div className="ambient ambient-two" /><nav className="topbar" aria-label="Navegación principal"><Link className="brand" href="/" aria-label="Edu Signal inicio"><span className="brand-block">E</span><span>EDU<br/><i>SIGNAL</i></span></Link><div className="nav-links"><Link href="/classrooms">Aulas</Link><Link href="/students">Estudiantes</Link><Link href="/rubrics">Rúbricas</Link><Link href="/evidence">Evidencias</Link></div><div className="nav-actions"><button className="bell" onClick={() => setToast("No hay alertas críticas.")} aria-label="Alertas">◌<b /></button><div className="account"><button className="profile" onClick={() => setToast(`Sesión activa: ${user.email}`)} aria-label={`Cuenta de ${user.displayName}`}>{initials}</button><button onClick={signOut} className="signout">Salir</button></div></div></nav><section className="hero"><div className="eyebrow"><span />ESPACIO DOCENTE</div><h1>Aprendizaje que<br/><em>deja señal.</em></h1><p>Convierte proyectos reales en evidencia clara, evaluación justa y credenciales que acompañan a cada estudiante.</p><div className="hero-buttons"><Link className="primary" href="/evidence">Registrar evidencia <span>→</span></Link><Link className="soft" href="/classrooms">Diseñar aula <span>↗</span></Link></div><div className="floating-card orbit-card"><span className="pixel-icon">✦</span><div><small>SEÑAL DE HOY</small><strong>Tu espacio está listo</strong></div></div><div className="floating-card badge-card"><span className="mini-cube">▪</span><div><small>PRÓXIMO PASO</small><strong>Crear tu primera rúbrica</strong></div></div><div className="blocks" aria-hidden="true"><span className="block b1"/><span className="block b2"/><span className="block b3"/><span className="block b4"/><span className="block b5"/><span className="block b6"/><div className="planet">◉</div></div></section><section className="signal-strip"><div><small>PLATAFORMA EDUCATIVA</small><strong>D1 <i>● conectada</i></strong></div><div className="bar-chart"><i/><i/><i/><i/><i/><i/><i/></div><p>Un lugar para diseñar, observar y compartir aprendizaje.</p></section><section className="content-grid"><div className="section-heading"><div><small>ESPACIO DE TRABAJO</small><h2>Construye el trayecto</h2></div></div><div className="student-grid">{highlights.map(([title, description, href, mark]) => <Link href={href} className="student-card workspace-card" key={title}><div className="avatar violet">{mark}</div><h3>{title}</h3><p>{description}</p><span>Explorar →</span></Link>)}</div></section><footer><span className="brand-block">E</span> EDU SIGNAL <i>· evidencias que importan</i><span>PRIVADO POR DISEÑO</span></footer>{toast && <div className="toast">✦ {toast}</div>}</main>;
}
