"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";

const types = ["instruction", "question", "prediction", "simulation", "external_link", "reflection", "reading"];
export default function ActivityForm({ classroomId, moduleId, activity }: { classroomId: string; moduleId: string; activity?: { id: string; title: string; instructions: string; activityType: string; config: unknown; required: boolean; requiresEvidence: boolean; status: string; position: number } }) {
  const initialConfig = activity?.config && typeof activity.config === "object" ? JSON.stringify(activity.config, null, 2) : "{}";
  const [type, setType] = useState(activity?.activityType ?? "instruction"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); let config: unknown; try { config = JSON.parse(String(form.get("config") ?? "{}")); } catch { setMessage("La configuración debe ser JSON válido."); setSaving(false); return; } const payload = { title: String(form.get("title") ?? ""), instructions: String(form.get("instructions") ?? ""), activityType: type, position: Number(form.get("position") ?? 1), required: form.get("required") === "on", requiresEvidence: form.get("requiresEvidence") === "on", config, status: String(form.get("status") ?? "draft") }; const response = await fetch(activity ? `/api/activities/${activity.id}` : `/api/modules/${moduleId}/activities`, { method: activity ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); setSaving(false); if (!response.ok) { setMessage(data.error ?? "No se pudo guardar."); return; } window.location.href = `/classrooms/${classroomId}/modules/${moduleId}`; }
  return <main className="studio-shell"><nav className="studio-nav"><Link className="brand" href="/classrooms"><span className="brand-block">E</span><span>EDU<br/><i>SIGNAL</i></span></Link><span className="teacher-chip">ACTIVIDAD</span></nav><section className="workspace-grid"><form className="modal workspace-form" onSubmit={submit}><small>{activity ? "EDITAR ACTIVIDAD" : "NUEVA ACTIVIDAD"}</small><h1>{activity ? "Ajusta el recorrido." : "Crea un siguiente paso."}</h1><label>Título<input name="title" required defaultValue={activity?.title} placeholder="Ej. Predicción inicial" /></label><label>Instrucciones<textarea name="instructions" defaultValue={activity?.instructions} placeholder="Qué debe hacer el estudiante..." /></label><label>Tipo<select name="activityType" value={type} onChange={(event) => setType(event.target.value)}>{types.map((item) => <option key={item}>{item}</option>)}</select></label><label>Configuración JSON<textarea name="config" defaultValue={initialConfig} rows={8} /></label><label>Posición<input name="position" type="number" min="1" defaultValue={activity?.position ?? 1} /></label><label className="checkbox-label"><input name="required" type="checkbox" defaultChecked={activity?.required ?? true} /> Actividad requerida</label><label className="checkbox-label"><input name="requiresEvidence" type="checkbox" defaultChecked={activity?.requiresEvidence ?? false} /> Requiere evidencia formal</label>{activity && <label>Estado<select name="status" defaultValue={activity.status}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label>}{message && <p className="auth-error" role="alert">{message}</p>}<button className="primary wide" disabled={saving}>{saving ? "Guardando…" : "Guardar actividad →"}</button></form></section></main>;
}
