"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
type Room = { id: string; name: string };
type Rubric = { rubric: { id: string; title: string; description: string | null }; criteria: Array<{ id: string; name: string; description: string }> };
export default function RubricStudio({ teacherName }: { teacherName: string }) {
  const [rooms, setRooms] = useState<Room[]>([]); const [rubrics, setRubrics] = useState<Rubric[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch("/api/classrooms").then((r) => r.json()), fetch("/api/rubrics").then((r) => r.json())]).then(([r, x]) => { setRooms(r.classrooms ?? []); setRubrics(x.rubrics ?? []); }); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const payload = { title: values.title, description: values.description, classroomId: values.classroomId, criteria: [{ name: values.criteriaName, description: values.criteriaDescription, maxScore: values.maxScore }] }; const response = await fetch("/api/rubrics", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "No se pudo guardar."); return; } setRubrics((current) => [{ rubric: data.rubric, criteria: data.rubric.criteria }, ...current]); event.currentTarget.reset(); setMessage("Rúbrica creada."); }
  return <main className="studio-shell"><nav className="studio-nav"><Link href="/" className="brand"><span className="brand-block">E</span><span>EDU<br/><i>SIGNAL</i></span></Link><div><span className="teacher-chip">DOCENTE · {teacherName}</span><Link className="signout" href="/">Inicio</Link></div></nav><header className="studio-hero compact-hero"><p>EVALUACIÓN JUSTA</p><h1>Criterios claros,<br/><em>aprendizaje visible.</em></h1><span>Diseña rúbricas que convierten la observación docente en retroalimentación útil y comparable.</span></header><section className="workspace-grid"><form className="modal workspace-form" onSubmit={submit}><small>NUEVA RÚBRICA</small><h2>Diseñar criterio</h2><label>Título<input name="title" required placeholder="Ej. Investigación con evidencia" /></label><label>Descripción<textarea name="description" placeholder="Propósito de la rúbrica" /></label><label>Aula<select name="classroomId" required defaultValue=""><option value="" disabled>Selecciona un aula</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label><label>Criterio<input name="criteriaName" required placeholder="Ej. Argumentación científica" /></label><label>Descripción del criterio<textarea name="criteriaDescription" required placeholder="Describe el desempeño esperado" /></label><label>Puntaje máximo<input name="maxScore" defaultValue="4" inputMode="numeric" /></label><button className="primary wide">Crear rúbrica →</button>{message && <p className="inline-message">{message}</p>}</form><section className="workspace-list"><div className="section-heading"><div><small>INSTRUMENTOS ACTIVOS</small><h2>Mis rúbricas</h2></div><strong>{rubrics.length}</strong></div>{rubrics.length ? rubrics.map((item) => <article className="workspace-item rubric-item" key={item.rubric.id}><div className="evidence-mark">✓</div><div><h3>{item.rubric.title}</h3><p>{item.criteria.length} criterio(s) · {item.rubric.description ?? "Sin descripción"}</p></div><span>{item.rubric.status}</span></article>) : <div className="empty-state"><b>Aún no hay rúbricas.</b><p>Crea la primera para evaluar con criterios compartidos.</p></div>}</section></section></main>;
}
