"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Evidence = { id: string; title: string; studentName: string; classroomName: string; moduleTitle?: string | null; activityTitle?: string | null; evidenceType: string; status: string; submittedAt?: string | null };
export default function EvidenceStudio({ teacherName }: { teacherName: string }) {
  const [items, setItems] = useState<Evidence[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  useEffect(() => { fetch("/api/evidence?status=submitted").then(async (response) => { if (!response.ok) throw new Error("load"); return response.json(); }).then((data) => { setItems(data.evidences ?? []); setState("ready"); }).catch(() => setState("error")); }, []);
  return <main className="studio-shell"><nav className="studio-nav"><Link className="brand" href="/"><span className="brand-block">E</span><span>EDU<br/><i>SIGNAL</i></span></Link><div><span className="teacher-chip">DOCENTE · {teacherName}</span><Link className="signout" href="/reviews">Revisiones</Link><Link className="signout" href="/">Inicio</Link></div></nav><header className="studio-hero compact-hero"><p>BITÁCORA VIVA</p><h1>Revisa lo que<br/><em>deja evidencia.</em></h1></header><section className="workspace-grid"><section className="workspace-list"><div className="section-heading"><div><small>ENTREGAS ENVIADAS</small><h2>Inbox de evidencias</h2></div><strong>{items.length}</strong></div>{state === "loading" && <p role="status">Cargando evidencias…</p>}{state === "error" && <p role="alert">No se pudieron cargar las evidencias.</p>}{state === "ready" && !items.length && <div className="empty-state"><b>Todavía no hay evidencias enviadas.</b></div>}{state === "ready" && items.map((item) => <Link className="workspace-item" href={`/evidence/${item.id}`} key={item.id}><div className="evidence-mark">✦</div><div><h3>{item.title}</h3><p>{item.studentName} · {item.classroomName} · {item.moduleTitle ?? "Sin módulo"} · {item.activityTitle ?? "Sin actividad"}</p><small>{item.evidenceType} · {item.submittedAt ? new Date(item.submittedAt).toLocaleString("es-ES") : "Sin fecha"}</small></div><span>{item.status}</span></Link>)}</section></section></main>;
}
