"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

type Room = { id: string; name: string };
type Person = { id: string; displayName: string; classroomId: string };
type Evidence = { id: string; title: string; studentName: string; kind: string; status: string };
export default function EvidenceStudio({ teacherName }: { teacherName: string }) {
  const [rooms, setRooms] = useState<Room[]>([]); const [people, setPeople] = useState<Person[]>([]); const [items, setItems] = useState<Evidence[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch("/api/classrooms").then((r) => r.json()), fetch("/api/students").then((r) => r.json()), fetch("/api/evidence").then((r) => r.json())]).then(([r, s, e]) => { setRooms(r.classrooms ?? []); setPeople(s.students ?? []); setItems(e.evidences ?? []); }); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const payload = Object.fromEntries(new FormData(event.currentTarget).entries()); const response = await fetch("/api/evidence", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) { setMessage(data.error ?? "No se pudo guardar."); return; } setItems((current) => [{ ...data.evidence, studentName: people.find((person) => person.id === data.evidence.studentId)?.displayName ?? "Estudiante", kind: "project", status: "submitted" }, ...current]); event.currentTarget.reset(); setMessage("Evidencia registrada."); }
  return <main className="studio-shell"><nav className="studio-nav"><Link href="/" className="brand"><span className="brand-block">E</span><span>EDU<br/><i>SIGNAL</i></span></Link><div><span className="teacher-chip">DOCENTE · {teacherName}</span><Link className="signout" href="/">Inicio</Link></div></nav><header className="studio-hero compact-hero"><p>BITÁCORA VIVA</p><h1>Lo que aprenden<br/><em>deja evidencia.</em></h1><span>Registra proyectos, actividades y entregables vinculados a cada estudiante y aula.</span></header><section className="workspace-grid"><form className="modal workspace-form" onSubmit={submit}><small>NUEVA EVIDENCIA</small><h2>Registrar aprendizaje</h2><label>Título<input name="title" required placeholder="Ej. Prototipo de filtro de agua" /></label><label>Descripción<textarea name="description" placeholder="¿Qué demuestra esta evidencia?" /></label><label>Aula<select name="classroomId" required defaultValue=""><option value="" disabled>Selecciona un aula</option>{rooms.map((room) => <option key={room.id} value={room.id}>{room.name}</option>)}</select></label><label>Estudiante<select name="studentId" required defaultValue=""><option value="" disabled>Selecciona un estudiante</option>{people.map((person) => <option key={person.id} value={person.id}>{person.displayName}</option>)}</select></label><button className="primary wide">Guardar evidencia →</button>{message && <p className="inline-message">{message}</p>}</form><section className="workspace-list"><div className="section-heading"><div><small>ÚLTIMAS ENTREGAS</small><h2>Evidencias</h2></div><strong>{items.length}</strong></div>{items.length ? items.map((item) => <article className="workspace-item" key={item.id}><div className="evidence-mark">✦</div><div><h3>{item.title}</h3><p>{item.studentName} · {item.kind}</p></div><span>{item.status}</span></article>) : <div className="empty-state"><b>La bitácora está vacía.</b><p>Registra la primera evidencia de aprendizaje.</p></div>}</section></section></main>;
}
